name: assignment App tests

on:
    pull_request:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./it_data/

        strategy:
            matrix:
                python-version: [3.1]

        env:
            MODE: "dev"
            
        
        steps:
            - uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: ${{ matrix.python-version }}
            
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install pyspark==3.5.0
            
            - name: Test App Code
              run: python ./main_task1.py