name: Run Task1 and Save Output

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-task1:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyspark==3.5.0

    - name: Run task1.py
      run: |
        python src/task1.py

    - name: Commit output files
      run: |
        git config --global user.email "your-email@example.com"
        git config --global user.name "Your Name"
        git add output/it_data/
        git commit -m "Add output data from task1.py"
        git push origin main

              