name: Run Task2 and Save Output

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-task1:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyspark==3.5.0

    - name: Run task2.py
      run: |
        python src/task2.py

    - name: Commit output files
      env:
        GITHUB_USER: "YoonsikYu"
        PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        git config --global user.email "sengwun2@naver.com"
        git config --global user.name "YoonsikYu"
        git add output/output/marketing_address_info/
        git commit -m "Add output data from task2.py"
        git push https://${{ env.GITHUB_USER }}:${{ env.PAT_TOKEN }}@github.com/YoonsikYu/assignment.git main 