name: Run Changed Python Scripts and Save Output

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-task1:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 2  # Fetch the last two commits to compare changes

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyspark==3.5.0

    - name: Identify changed Python scripts
      id: changes
      run: |
        CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD | grep "^src/.*\.py$")
        echo "Changed files: $CHANGED_FILES"
        echo "::set-output name=changed_files::$CHANGED_FILES"

    - name: Run changed Python scripts
      if: steps.changes.outputs.changed_files != ''
      run: |
        for script in ${{ steps.changes.outputs.changed_files }}; do
          echo "Running $script"
          python "$script"
        done

    - name: Commit output files
      if: steps.changes.outputs.changed_files != ''
      env:
        GITHUB_USER: "YoonsikYu"
        PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        git config --global user.email "sengwun2@naver.com"
        git config --global user.name "YoonsikYu"
        git add output/
        git commit -m "Add output data from changed scripts"
        git push https://${{ env.GITHUB_USER }}:${{ env.PAT_TOKEN }}@github.com/YoonsikYu/assignment.git main